# Check https://circleci.com/docs/2.0/language-java/ for more details
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout 
      - run: mvn integration-test
